name: External GitLab to GitHub migration
description: Perform a migration from External GitLab to GitHub
title: "External GitLab to GitHub migration"
labels: ["migration", "external-gitlab"]
body:
  - type: textarea
    id: logs
    attributes:
      label: Repositories
      description: Please enter the repositories that you would like to migrate from GitLab to GitHub
      render: csv
      placeholder: |
        group1,repo1
        group2,repo2
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Target repository visibility
      description: Please select the visibility for the repositories on GitHub after they have been migrated
      options:
        - Private
        - Internal
    validations:
      required: true
