name: CI

on: push

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - run: npm ci

      - run: npm run format:check

      - run: npm run lint:check
