name: Migration from GitHub Enterprise Server

on:
  issue_comment:
    types: [created]

jobs:
  export:
    if: contains(github.event.issue.labels.*.name, 'github-enterprise-server')
    uses: github/migrations-via-actions-v3-from-gitlab-ghes-to-ghec/.github/workflows/shared-github-enterprise-server-export.yml@main
    with:
      runner: ghes-migration
      ghes-ssh-host: github.steffenhiller.com
    secrets:
      GHES_ADMIN_USERNAME: ${{ secrets.GHES_ADMIN_USERNAME }}
      GHES_ADMIN_TOKEN: ${{ secrets.GHES_ADMIN_TOKEN }}

  import:
    needs: export
    uses: github/migrations-via-actions-v3-from-gitlab-ghes-to-ghec/.github/workflows/shared-github-enterprise-cloud-import.yml@main
    with:
      user-mappings-path: ../../user-mappings.csv
      # Example: https://github.example.com or https://github.com
      user-mappings-source-url: https://github.com
    secrets:
      GHEC_ADMIN_TOKEN: ${{ secrets.GHEC_ADMIN_TOKEN }}
      GHEC_TARGET_ORGANIZATION: ${{ secrets.GHEC_TARGET_ORGANIZATION }}
