name: GEI Migration from GitHub Enterprise Server

on:
  issue_comment:
    types: [created]

jobs:
  migrate:
    uses: ./.github/workflows/shared-github-enterprise-cloud-gei.yml
    with:
      user-mappings-path: user-mappings.csv
      user-mappings-source-url: https://ghes67.tspascoal.com
    secrets:
      GHEC_ADMIN_TOKEN: ${{ secrets.GHEC_ADMIN_TOKEN }}
      GHES_ADMIN_TOKEN: ${{ secrets.GHES_ADMIN_TOKEN }}
      GEI_AZURE_CONNECTION_STRING: ${{ secrets.GEI_AZURE_CONNECTION_STRING }}
      