name: Migration from External GitLab

on:
  issue_comment:
    types: [created]

jobs:
  export:
    if: contains(github.event.issue.labels.*.name, 'external-gitlab')
    uses: ./.github/workflows/shared-gitlab-export.yml
    with:
      GITLAB_USERNAME: ${{ vars.EXTERNAL_GITLAB_USERNAME}}
      GITLAB_API_ENDPOINT: ${{ vars.EXTERNAL_GITLAB_API_ENDPOINT }}
    secrets:
      GITLAB_API_PRIVATE_TOKEN: ${{ secrets.EXTERNAL_GITLAB_API_PRIVATE_TOKEN }}

  import:
    needs: export
    uses: ./.github/workflows/shared-github-enterprise-cloud-import.yml
    with:
      user-mappings-path: ../../user-mappings.csv
      user-mappings-source-url: ${{ vars.EXTERNAL_GITLAB_MAPPING_SOURCE_URL}} # https://gitlab.example.com
      GHEC_TARGET_ORGANIZATION: ${{ vars.GHEC_TARGET_ORGANIZATION }}
    secrets:
      GHEC_ADMIN_TOKEN: ${{ secrets.GHEC_ADMIN_TOKEN }}
