name: Migration from External GitLab

on:
  issue_comment:
    types: [created]

jobs:
  export:
    if: contains(github.event.issue.labels.*.name, 'external-gitlab')
    uses: ./.github/workflows/shared-gitlab-export.yml
    secrets:
      GITLAB_USERNAME: ${{ secrets.EXTERNAL_GITLAB_USERNAME }}
      GITLAB_API_PRIVATE_TOKEN: ${{ secrets.EXTERNAL_GITLAB_API_PRIVATE_TOKEN }}
      GITLAB_API_ENDPOINT: ${{ secrets.EXTERNAL_GITLAB_API_ENDPOINT }}

  import:
    needs: export
    uses: ./.github/workflows/shared-github-enterprise-cloud-import.yml
    with:
      user-mappings-path: ../../user-mappings.csv
      user-mappings-source-url: https://gitlab.example.com
    secrets:
      GHEC_ADMIN_TOKEN: ${{ secrets.GHEC_ADMIN_TOKEN }}
      GHEC_TARGET_ORGANIZATION: ${{ secrets.GHEC_TARGET_ORGANIZATION }}
