# Parses migration issue and creates a comment with next step
#
# Required secrets:
#
#   - GHEC_TARGET_ORGANIZATION:
#     The organization on GitHub.com to import into (needs to have ECI feature flag enabled)

name: Migration (Prepare)

on:
  issues:
    types: [opened, edited]

jobs:
  prepare:
    name: Prepare Migration
    runs-on: ubuntu-latest

    if: github.event_name == 'issues' &&
      (github.event.action == 'opened' || github.event.action == 'edited') &&
      contains(github.event.issue.labels.*.name, 'migration')

    steps:
      - name: Check out scripts
        uses: actions/checkout@v2

      - name: Post prepare message
        uses: actions/github-script@v5
        with:
          script: |
            const options = { targetOrganization: '${{ secrets.GHEC_TARGET_ORGANIZATION }}' }
            await require('./.github/scripts/prepare.js')({github, context, options})
