name: Migration from GitHub Enterprise Server [GEI]

on:
  issue_comment:
    types: [created]

jobs:
  migrate:
    if: contains(github.event.issue.labels.*.name, 'github-enterprise-server') &&
        contains(github.event.issue.labels.*.name, 'migration') &&
        contains(github.event.issue.labels.*.name, 'gei') &&
        !startsWith(github.event.comment.body, '/delete-repositories')
    uses: ./.github/workflows/shared-github-enterprise-cloud-gei.yml
    with:
      GHEC_TARGET_ORGANIZATION: ${{ vars.GHEC_TARGET_ORGANIZATION }}
    secrets:
      GHEC_ADMIN_TOKEN: ${{ secrets.GHEC_ADMIN_TOKEN }}
      GHES_ADMIN_TOKEN: ${{ secrets.GHES_ADMIN_TOKEN }}
      GEI_AZURE_CONNECTION_STRING: ${{ secrets.GEI_AZURE_CONNECTION_STRING }}
      
