name: Migration from GitHub Enterprise Server

on:
  issue_comment:
    types: [created]

jobs:
  export:
    if: contains(github.event.issue.labels.*.name, 'github-enterprise-server') && !contains(github.event.issue.labels.*.name, 'gei')
    uses: ./.github/workflows/shared-github-enterprise-server-export.yml
    with:
      runner: ghes-migration
      ghes-ssh-host: ${{ vars.GHES_SSH_HOST }} # github.steffenhiller.com
      GHES_ADMIN_USERNAME: ${{vars.GHES_ADMIN_USERNAME}}}
    secrets:
      GHES_ADMIN_TOKEN: ${{ secrets.GHES_ADMIN_TOKEN }}

  import:
    needs: export
    uses: ./.github/workflows/shared-github-enterprise-cloud-import.yml
    with:
      user-mappings-path: ../../user-mappings.csv
      user-mappings-source-url: ${{ vars.GH_USER_MAPPING_SOURCE_URL }} # https://github.example.com
      GHEC_TARGET_ORGANIZATION: ${{ vars.GHEC_TARGET_ORGANIZATION }}
    secrets:
      GHEC_ADMIN_TOKEN: ${{ secrets.GHEC_ADMIN_TOKEN }}
