name: Migration from Internal GitLab

on:
  issue_comment:
    types: [created]

jobs:
  export:
    if: contains(github.event.issue.labels.*.name, 'internal-gitlab')
    uses: ./.github/workflows/shared-gitlab-export.yml
    with:
      runner: internal
      setup-ruby: false
    secrets:
      GITLAB_USERNAME: ${{ secrets.INTERNAL_GITLAB_USERNAME }}
      GITLAB_API_PRIVATE_TOKEN: ${{ secrets.INTERNAL_GITLAB_API_PRIVATE_TOKEN }}
      GITLAB_API_ENDPOINT: ${{ secrets.INTERNAL_GITLAB_API_ENDPOINT }}

  import:
    needs: export
    uses: ./.github/workflows/shared-github-enterprise-cloud-import.yml
    with:
      user-mappings-path: ../../user-mappings.csv
      user-mappings-source-url: https://gitlab.example.internal
    secrets:
      GHEC_ADMIN_TOKEN: ${{ secrets.GHEC_ADMIN_TOKEN }}
      GHEC_TARGET_ORGANIZATION: ${{ secrets.GHEC_TARGET_ORGANIZATION }}
