name: Migration from Internal GitLab

on:
  issue_comment:
    types: [created]

jobs:
  export:
    if: contains(github.event.issue.labels.*.name, 'internal-gitlab')
    uses: ./.github/workflows/shared-gitlab-export.yml
    with:
      runner: internal
      setup-ruby: false
      GITLAB_USERNAME: ${{ vars.INTERNAL_GITLAB_USERNAME}}
      GITLAB_API_ENDPOINT: ${{ vars.INTERNAL_GITLAB_API_ENDPOINT }}
    secrets:
      GITLAB_API_PRIVATE_TOKEN: ${{ secrets.INTERNAL_GITLAB_API_PRIVATE_TOKEN }}

  import:
    needs: export
    uses: ./.github/workflows/shared-github-enterprise-cloud-import.yml
    with:
      user-mappings-path: ../../user-mappings.csv
      user-mappings-source-url: ${{ vars.INTERNAL_GITLAB_MAPPING_SOURCE_URL}} # https://gitlab.example.internal 
      GHEC_TARGET_ORGANIZATION: ${{ vars.GHEC_TARGET_ORGANIZATION }}
    secrets:
      GHEC_ADMIN_TOKEN: ${{ secrets.GHEC_ADMIN_TOKEN }}
